name: Build initial checkpoints image/container

on:
  workflow_dispatch:
    inputs:
      tags:
        description: The tags of the built image (e.g. repo/image:version)
        # default: cgdoc/casia-olhwcr-tf:latest
        required: true

jobs:
  build_inital:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.init
          push: true
          tags: ${{ github.event.inputs.tags }}